[db]
url = "postgresql://postgres:postgres@localhost:1616/warmlight_test"
timeoutMs = 3000

[bot]
token = "..."
webhookUrl = "https://mysite.com/webhook.url"
certFile = "certfile.cert"
privKeyFile = "priv.key"
logPath = "log/warmlight.log"
isDev = true
defaultActiveSourceTimeoutMins = 60
deactivatorIntervalMins = 10
port = 443

